import { assertEquals } from "https://deno.land/std@0.167.0/testing/asserts.ts";
import { extractData, phase1, phase2 } from "./lib.ts";

const input = `..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............`;

Deno.test("Extract data", () => {
  assertEquals(extractData(input).length, 22);
});

Deno.test("Phase 1", () => {
  assertEquals(phase1(input), 110);
});

Deno.test("Phase 2", () => {
  assertEquals(phase2(input), 20);
});
